/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdRevenueMetrics {
  'clicks' : bigint,
  'revenue' : number,
  'date' : string,
  'impressions' : bigint,
}
export interface AdSenseConfig {
  'headerAdUnitId' : string,
  'enableInContentAds' : boolean,
  'enableFooterBanner' : boolean,
  'publisherId' : string,
  'sidebarAdUnitId' : string,
  'enableSidebarAds' : boolean,
  'footerAdUnitId' : string,
  'inContentAdUnitId' : string,
  'enableHeaderBanner' : boolean,
}
export type ExternalBlob = Uint8Array;
export interface FileMetadata {
  'id' : string,
  'blob' : ExternalBlob,
  'fileName' : string,
  'uploadTime' : Time,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteFile' : ActorMethod<[string], undefined>,
  'getAdSenseConfig' : ActorMethod<[], AdSenseConfig>,
  'getAggregateRevenue' : ActorMethod<[string, string], AdRevenueMetrics>,
  'getAllRevenueMetrics' : ActorMethod<[], Array<AdRevenueMetrics>>,
  'getCallerFiles' : ActorMethod<[], Array<FileMetadata>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFileMetadata' : ActorMethod<[string], FileMetadata>,
  'getRevenueByRange' : ActorMethod<[string, string], Array<AdRevenueMetrics>>,
  'getRevenueMetrics' : ActorMethod<[string], AdRevenueMetrics>,
  'getTrafficCounter' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'incrementAndGetTrafficCounter' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordAdMetrics' : ActorMethod<[string, bigint, bigint, number], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAdSenseConfig' : ActorMethod<[AdSenseConfig], undefined>,
  'uploadFile' : ActorMethod<[string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];