/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdSenseConfig = IDL.Record({
  'headerAdUnitId' : IDL.Text,
  'enableInContentAds' : IDL.Bool,
  'enableFooterBanner' : IDL.Bool,
  'publisherId' : IDL.Text,
  'sidebarAdUnitId' : IDL.Text,
  'enableSidebarAds' : IDL.Bool,
  'footerAdUnitId' : IDL.Text,
  'inContentAdUnitId' : IDL.Text,
  'enableHeaderBanner' : IDL.Bool,
});
export const AdRevenueMetrics = IDL.Record({
  'clicks' : IDL.Nat,
  'revenue' : IDL.Float64,
  'date' : IDL.Text,
  'impressions' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const FileMetadata = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
  'fileName' : IDL.Text,
  'uploadTime' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteFile' : IDL.Func([IDL.Text], [], []),
  'getAdSenseConfig' : IDL.Func([], [AdSenseConfig], ['query']),
  'getAggregateRevenue' : IDL.Func(
      [IDL.Text, IDL.Text],
      [AdRevenueMetrics],
      ['query'],
    ),
  'getAllRevenueMetrics' : IDL.Func([], [IDL.Vec(AdRevenueMetrics)], ['query']),
  'getCallerFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFileMetadata' : IDL.Func([IDL.Text], [FileMetadata], ['query']),
  'getRevenueByRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(AdRevenueMetrics)],
      ['query'],
    ),
  'getRevenueMetrics' : IDL.Func([IDL.Text], [AdRevenueMetrics], ['query']),
  'getTrafficCounter' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'incrementAndGetTrafficCounter' : IDL.Func([], [IDL.Nat], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordAdMetrics' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Float64],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAdSenseConfig' : IDL.Func([AdSenseConfig], [], []),
  'uploadFile' : IDL.Func([IDL.Text, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdSenseConfig = IDL.Record({
    'headerAdUnitId' : IDL.Text,
    'enableInContentAds' : IDL.Bool,
    'enableFooterBanner' : IDL.Bool,
    'publisherId' : IDL.Text,
    'sidebarAdUnitId' : IDL.Text,
    'enableSidebarAds' : IDL.Bool,
    'footerAdUnitId' : IDL.Text,
    'inContentAdUnitId' : IDL.Text,
    'enableHeaderBanner' : IDL.Bool,
  });
  const AdRevenueMetrics = IDL.Record({
    'clicks' : IDL.Nat,
    'revenue' : IDL.Float64,
    'date' : IDL.Text,
    'impressions' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const FileMetadata = IDL.Record({
    'id' : IDL.Text,
    'blob' : ExternalBlob,
    'fileName' : IDL.Text,
    'uploadTime' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteFile' : IDL.Func([IDL.Text], [], []),
    'getAdSenseConfig' : IDL.Func([], [AdSenseConfig], ['query']),
    'getAggregateRevenue' : IDL.Func(
        [IDL.Text, IDL.Text],
        [AdRevenueMetrics],
        ['query'],
      ),
    'getAllRevenueMetrics' : IDL.Func(
        [],
        [IDL.Vec(AdRevenueMetrics)],
        ['query'],
      ),
    'getCallerFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFileMetadata' : IDL.Func([IDL.Text], [FileMetadata], ['query']),
    'getRevenueByRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(AdRevenueMetrics)],
        ['query'],
      ),
    'getRevenueMetrics' : IDL.Func([IDL.Text], [AdRevenueMetrics], ['query']),
    'getTrafficCounter' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'incrementAndGetTrafficCounter' : IDL.Func([], [IDL.Nat], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordAdMetrics' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Float64],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAdSenseConfig' : IDL.Func([AdSenseConfig], [], []),
    'uploadFile' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };